### ISSUE TITLE
InstanceBuilder should parse the serialized content and build the related instance at call of GetInstance() instead of doing it at ctor.

### ISSUE THREAD

**Issue by nagyL** [csnemes/shapeshifter#6]
Actually InstanceBuilder creates the instance of the underlying type and automatically fills-up the matching fields from the related serialized content at construction time. Unfortunatelly there is no way for interaction. 
There are some situations where a complex type's field changed in type (but the field's name remains the same) and there is no way to create a converter from the field's old type to the new one (simply because we don't want the old type to be converted to the new one in the whole serialization context). In such situation the construction of InstanceBuilder fail.
A suggested solution is to only inject the reader in the constructor without instantiating the underlying type. Conform that the SetMember() also just registers a map between a field and the desired value used finally by the call of GetInstance(). GetInstance() should be the right place to instantiate the underlying type and where the mappings registered by the SetMember() calls will take in consideration followed by the "auto-fill" of the rest of fields. In that way it is possible to interact on a field before the "auto-fill" process takes place.

**Comment by csnemes** [comment]
done in 1.3
