### ISSUE TITLE
Feature request: Snapshot.exe should display the version of a specified type in the specified snapshot

### ISSUE THREAD

**Issue by nagyL** [csnemes/shapeshifter#7]
There are some situations when deploying a new release some reference data become obsolete. To maintain backward compatibility the obsolete items must be mapped to their active correspondents. Such mapping could take place in shapeshifter converters, however to write the converter the version of the given type must be known. 
It could be helpfull to extend the Snapshot.exe to return the version of a specified type in the specified snapshot.

**Comment by csnemes** [comment]
added view verb to snapshot to see the list of current types with version (v1.3)
